/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jui;

public class App {

    public static void main(String[] args) throws InterruptedException {

        Global.getWindow().render();
    }
}
